spring.application.name=ItAu
server.servlet.context-path=/api/v1
server.port=8080

# ===============================
# Actuator Config
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ===============================
# Swagger / OpenAPI Config
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Logging Config
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/password-validator.log